project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!topics-2023/2023-12-09-earthdataaccess-intro/*_Harmony.ipynb"
    - "!topics-2023/2023-12-19-earthdatalogin-intro/Earthdata/*_Harmony.qmd"
    - "!topics-2023/2023-12-19-earthdatalogin-intro/Earthdata_*"
    - "!topics-2023/2023-12-19-earthdatalogin-intro/earthdatalogin_sst.qmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "NOAA Fisheries HackHours"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/NOAAHackDays
  repo-url: https://github.com/nmfs-opensci/NOAAHackDays
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)

  navbar:
    background: primary
    search: true
    left:
      - href: index.md
        text: Home
      - text: Topics
        menu: 
          - text: HackHours 2023
            href: topics-2023/index.md
          - text: HackHours 2024
            href: topics-2024/index.md
    right: 
      - icon: server
        href: https://dhub.opensci.live/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/nmfs-opensci/NOAAHackDays/discussions
        text: "Discussions"
      - icon: github
        href: https://github.com/nmfs-opensci/NOAAHackDays
        text: "repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"
  sidebar:
    - id: home
      logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
      style: "docked"
      collapse-level: 1
      toc-expand: false
      pinned: true
      align: left
      contents:
        - href: about.md
          text: About
        - href: nav.md
          text: Navigation
        - href: setup.md
          text: Set-up
        - href: coc.md
          text: Code of Conduct
        - href: reuse.md
          text: Reuse Statement
        - text: "---"
        - text: HackHours 2023
          href: topics-2023/index.md
        - text: HackHours 2024
          href: topics-2024/index.md
    - id: topics-2023
      logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
      style: "docked"
      collapse-level: 1
      toc-expand: false
      pinned: true
      align: left
      contents:
        - text: HackHours 2023
          href: topics-2023/index.md
        - text: "---"
        - text: Earth Data Access in Python
          href: topics-2023/2023-12-09-earthdataaccess-intro/index.qmd
        - text: Earth Data Login in R
          href: topics-2023/2023-12-19-earthdatalogin-intro/index.qmd
    - id: topics-2024
      logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
      style: "docked"
      collapse-level: 1
      toc-expand: false
      pinned: true
      align: left
      contents:
        - text: HackHours 2024
          href: topics-2024/index.md
        - text: "---"
        - text: R - CoastWatch tutorials
          href: topics-2024/2024-03-22-Coastwatch-R/index.qmd
        - text: Python - CoastWatch tutorials
          href: topics-2024/2024-03-15-Coastwatch-Py/index.qmd
        - text: Python - ArcGIS
          href: topics-2024/2024-04-05-ArcGIS/index.qmd
        - text: Python - CMIP6 climate forecasts
          href: topics-2024/2024-04-12-cmip6/index.qmd
        - text: Python - Parallel Computing
          href: topics-2024/2024-04-19-dask/index.qmd
        - text: R - VAST
          href: topics-2024/2024-04-25-vast/index.qmd
        - text: Python - echopype 2
          href: topics-2024/2024-04-26-echopype/index.qmd
        - text: Python - PACE Ocean Color
          href: topics-2024/2024-05-17-ocean-color/index.qmd
        - text: R - sits R package
          href: topics-2024/2024-05-24-sits/index.qmd
        - text: Python - CEFI Portal
          href: topics-2024/2024-06-14-cefi/index.qmd
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
